### PR TITLE
chore(source): fixes concurrent issue where resources are not closed

### LINKED ISSUE #12: Possibly not closing all resources for SourceTask
Current behaviour is modelled against the Kafka JDBC connector, which essentially keeps a `running` flag that is set to false on stop. Resources are closed once poll is called and running is false, as opposed to in stop, since if already polling we might not those resources (stop is called from another thread).

However I'm not 100% sure that the following is not possible:

1. `poll()` is called
1. `stop()` is called and `running` is set to false, but poll is already running
1. `poll()` returns with some jobs (so nothing closed)

If `poll()` isn't called again then resources aren't closed. Should verify this.

### PR DESCRIPTION
**Pull request by npepinpe**
closes #12

### CODE REVIEW

**Comment by npepinpe** [comment]
@Zelldon If you don't have time for this just tell me, I'd just like to challenge if the bug was because of what I thought and would explain the issues I saw.

For a source connector, there are two important methods that are called from different threads: `poll()` and `stop()`. The first is called from the task thread, the second is almost always called from a different, controller thread.

Here we want to close the job worker and client as resources when being asked to stopped. The problem is, if we're already polling, we don't want to just kill everything and can afford to let the poll finish.

The implementation before was too naive and relied on the fact that poll was called often enough that you were usually polling while stopped was being called, but I verified that we weren't closing all resources.

This one uses a tri-state reference so that we close the resources after polling if we're in stopped state, or if we're being called to stop and aren't polling we also close the resources (atomically).

Also includes some minor refactoring but the main part is that I think what was happening is we weren't closing all resources when a task was stopped, so we'd have two job workers running, one in a live task, the other in a dead one, and if the one in the dead one was the first to activate jobs then the live one would never see anything (and the dead one would push to a queue that was never consumed).

File: src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java [hunk 1]
```diff
@@ -68,39 +68,38 @@ public void start(final Map<String, String> props) {
...
-        LOGGER.trace("No jobs available, block for {}ms", JOB_QUEUE_TIMEOUT_MS);
-        final ActivatedJob job = jobs.poll(JOB_QUEUE_TIMEOUT_MS, TimeUnit.MILLISECONDS);
-        if (job == null) {
-          LOGGER.trace("No jobs available, returning control to caller");
-          return null;
-        }
+    final List<SourceRecord> records = new ArrayList<>();
+    if (taskState.compareAndSet(TaskState.STARTED, TaskState.POLLING)) {
+      drainQueueBlocking().stream().map(this::transformJob).forEach(records::add);
+      taskState.compareAndSet(TaskState.POLLING, TaskState.STARTED);
```
Comment (Zelldon) [inline src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java]: What if this fails?

File: src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java [hunk 2]
```diff
@@ -68,39 +68,38 @@ public void start(final Map<String, String> props) {
     workers =
         jobTypes.stream().map(type -> this.newWorker(config, type)).collect(Collectors.toList());
 
-    running.set(true);
+    if (!taskState.compareAndSet(TaskState.STOPPED, TaskState.STARTED)) {
```
Comment (Zelldon) [inline src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java]: I'm not sure whether this state handling is necessary or not

File: src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java [hunk 3]
```diff
@@ -118,8 +117,22 @@ public String version() {
...
   }
 
+  private void closeIfStopped() {
+    if (taskState.get() == TaskState.STOPPED) {
+      close();
+    }
+  }
+
+  private TaskState closeUnlessPolling(final TaskState currentState) {
+    if (currentState != TaskState.POLLING) {
```
Comment (Zelldon) [inline src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java]: Does ths make sense?

Comment (Zelldon) [reply src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java]: I mean then you still have one which is in state polling but actually already closed?

File: src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java (hunk 2 above)
Comment (npepinpe) [reply src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java]: I couldn't find anything on how often start/stop is called in the lifetime of a task, so I figured a fail-safe could be useful. It's probably safe to assume that start is only called if the task is new or it was previously stopped before, but I figured just in case (plus it's not the hot path so a little performance hit there isn't a huge deal I think).

File: src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java (hunk 1 above)
Comment (Zelldon) [reply src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java]: But if stop is called it will not change the POLLING state right? How we clean up if we are in the polling phase :sweat_smile:

File: src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java (hunk 3 above)
Comment (npepinpe) [reply src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java]: My understanding here is that `closeUnlessPolling` is called to atomically update the current state. So if we're already polling we don't close anything and transition to stopped, and `poll()` will close everything once it's not polling any more. If we're not polling it's safe to close everything.

Comment (Zelldon) [reply src/main/java/io/zeebe/kafka/connect/source/ZeebeSourceTask.java]: Aaah yes have overseen this closeIfStopped ok then it makes sense thanks
